Examples Todo app
sberdevices/salutejs pull request #124
Opened 2021-04-28 08:01 UTC by sasha-tlt

2021-04-29 11:28 UTC, Turanchoks commented on examples/todo/src/scenario/scenario.ts
> +const createRegexpMatcher = (regexp: RegExp) => (req: SaluteRequest) => {
regexp занести в матчеры и пошарить между todo и чатапом

2021-04-29 11:28 UTC, Turanchoks commented on examples/todo/src/scenario/scenario.ts
> +        handle: addNote as SaluteHandler,
зачем тут as'ы?

2021-04-29 11:30 UTC, Turanchoks commented on examples/todo/src/pages/index.tsx
> +const IndexPage = memo(() => {
зачем тут мемо?

2021-04-29 11:47 UTC, Turanchoks approved these changes

2021-04-29 11:47 UTC, Turanchoks approved these changes

2021-05-05 07:52 UTC, sasha-tlt commented on examples/todo/src/scenario/scenario.ts
> +        handle: addNote as SaluteHandler,
поправил

2021-05-05 08:04 UTC, awinogradov commented on examples/todo/next.config.js
> +const withTM = require('next-transpile-modules')(['@sberdevices/assistant-client']);
А что это? Почему это?

2021-05-05 08:05 UTC, awinogradov commented on examples/todo/src/Components/GlobalStyles.tsx
> +                switch (character) {
Объект-мапа точно будет моднее чем свитч)

2021-05-05 08:07 UTC, awinogradov commented on examples/todo/src/pages/index.tsx
> +    // @ts-ignore
Может https://nextjs.org/docs/advanced-features/dynamic-import#basic-usage ?

2021-05-05 08:09 UTC, sasha-tlt commented on examples/todo/next.config.js
> +const withTM = require('next-transpile-modules')(['@sberdevices/assistant-client']);
Подглядел у Паши, как-то не так собираем `assistant-client`

2021-05-05 08:09 UTC, awinogradov commented on examples/todo/src/pages/index.tsx
> +        assistantRef.current?.sendData({ action: { action_id: 'done', parameters: { title } } });
createAction?

2021-05-05 08:10 UTC, awinogradov commented on examples/todo/src/pages/index.tsx
> +        import('@sberdevices/assistant-client').then(({ /* createAssistant, */ createSmartappDebugger }) => {
А почему именно так надо подключать?

2021-05-05 08:11 UTC, awinogradov commented on examples/todo/src/pages/index.tsx
> +import { Container, Row, Col } from '@sberdevices/plasma-ui';
А почему часть компонентов импортируется по полному пути, а часть из корня пакета?

2021-05-05 08:12 UTC, awinogradov commented on examples/todo/src/pages/index.tsx
> +                    case 'navigation':
чет я не понял почему 76 строка не здесь

2021-05-05 08:14 UTC, awinogradov commented on examples/todo/src/scenario/handlers.ts
> +    const item = req.state?.item_selector?.items.find((i) => (i.title || '').toLowerCase() === note.toLowerCase());
в matchers есть selectItem

2021-05-05 08:16 UTC, awinogradov commented on examples/todo/src/scenario/scenario.ts
> +        match: match(regexp(/^(запиши|напомни|добавь запись) (?<note>.+)$/i)),
match это compose. Если матчер один, как здесь regexp, то заворачивать в match не нужно

2021-05-05 08:17 UTC, awinogradov commented on examples/todo/src/scenario/scenario.ts
> +    intents: createIntents({}),
https://github.com/sberdevices/salutejs/pull/122

2021-05-05 08:18 UTC, awinogradov commented on examples/todo/src/scenario/scenario.ts
> +    const sessionId = request.uuid.userId;
@Turanchoks а где тот самый правильный вариант доставать sessionId?

2021-05-05 08:20 UTC, awinogradov requested changes
Осталось немножк ;)

2021-05-05 08:22 UTC, awinogradov commented on examples/todo/next.config.js
> +const withTM = require('next-transpile-modules')(['@sberdevices/assistant-client']);
Надо бы разобраться. Мы же пример для людей делаем, они же просто начнут копировать это.

2021-05-05 14:13 UTC, sasha-tlt commented on examples/todo/src/pages/index.tsx
> +    // @ts-ignore
`next/dynamic` для react-компонент

2021-05-05 16:20 UTC, awinogradov commented on examples/todo/next.config.js
> +const withTM = require('next-transpile-modules')(['@sberdevices/assistant-client']);
@Turanchoks вотс хэппенинг?

2021-05-05 16:28 UTC, awinogradov commented on examples/todo/src/pages/index.tsx
> +    // @ts-ignore
Ок, а почем нельзя просто заимпортить модуль?  Падает из-за завязок на window?

2021-05-05 19:22 UTC, sasha-tlt commented on examples/todo/next.config.js
> +const withTM = require('next-transpile-modules')(['@sberdevices/assistant-client']);
Это не нужно, поправил в assistant-client

2021-05-05 19:22 UTC, sasha-tlt commented on examples/todo/src/pages/index.tsx
> +    // @ts-ignore
Да, из-за ssr

2021-05-05 19:29 UTC, awinogradov commented on examples/todo/next.config.js
> +const withTM = require('next-transpile-modules')(['@sberdevices/assistant-client']);
Знач удалить надо?)

2021-05-05 19:29 UTC, awinogradov commented on examples/todo/src/pages/index.tsx
> +        import('@sberdevices/assistant-client').then(({ /* createAssistant, */ createSmartappDebugger }) => {
Тут таки не понятно

2021-05-06 05:33 UTC, sasha-tlt commented on examples/todo/src/pages/index.tsx
> +        import('@sberdevices/assistant-client').then(({ /* createAssistant, */ createSmartappDebugger }) => {
здесь падал assistant-client в ssr, поправил assistant-client. Уберу канарейку, когда смержим фикс в assistant-client

2021-05-06 05:34 UTC, sasha-tlt commented on examples/todo/next.config.js
> +const withTM = require('next-transpile-modules')(['@sberdevices/assistant-client']);
На самом деле, это не работало) Удалил

2021-05-06 09:40 UTC, Turanchoks commented on examples/todo/src/scenario/scenario.ts
> +    const sessionId = request.uuid.userId;
Пока так сайдет, userId на самом деле не userId, он уникальный на девайс, а новая сессия диалоговая начинается, когда new_session true. Можно это просто в доке дописать или в примере

2021-05-06 09:44 UTC, awinogradov approved these changes

2021-05-06 12:24 UTC, merged