Проверка requestMap[data.messageId] в сценарии echo
sberdevices/salutejs pull request #179
Opened 2021-06-17 14:09 UTC by AlexandrGil

2021-06-17 17:00 UTC, awinogradov commented
Спасибо большое! Но кажется, что коммиты можно посквошить) Коммитов сильно больше чем правок в коде)

2021-06-21 16:04 UTC, awinogradov commented
@AlexandrGil посковошишь?

2021-06-21 16:05 UTC, awinogradov requested changes
Почистить историю

2021-06-21 22:28 UTC, closed without merging

2021-06-21 22:28 UTC, AlexandrGil commented
Чуть позже сделаю)

2021-06-21 22:32 UTC, awinogradov commented
🤷🏼‍♂️