memory. firebase initial
sberdevices/salutejs pull request #82
Opened 2021-03-29 22:37 UTC by snyuryev

2021-03-30 07:40 UTC, snyuryev commented
опечатка
```
path: ['Some'],
```

дб
```
path: [''],
```

2021-03-30 11:12 UTC, awinogradov requested changes
Сборка упала из-за ненужной циклической зависмости на `@salutejs/memory`

2021-03-30 11:12 UTC, awinogradov commented on packages/memory/src/lib/firebase.ts
> +// eslint-disable-next-line no-unused-vars
Disable надо убрать

2021-03-30 11:12 UTC, awinogradov commented on packages/memory/src/lib/firebase.ts
> + *
Надо бы чет написать

2021-03-30 11:12 UTC, awinogradov commented on packages/memory/src/lib/firebase.ts
> +const functions = require('firebase-functions');
Это всё надо добавить в зависимости пакета

2021-03-30 11:12 UTC, awinogradov commented on packages/memory/src/lib/firebase.ts
> +import {SaluteSessionStorage} from '@salutejs/memory';
Код явно не проходил через prettier

2021-03-30 11:12 UTC, awinogradov commented on packages/memory/src/lib/firebase.ts
> +   * @param {id} id id.
Описания переменных надо бы почекать

2021-03-30 11:12 UTC, awinogradov commented on packages/memory/src/lib/firebase.ts
> +import {SaluteSessionStorage} from '@salutejs/memory';
Это можно взять из соседнего файла, но зачем?

2021-03-30 11:12 UTC, awinogradov commented on packages/memory/src/lib/firebase.ts
> +    return admin.database().ref(`users/${id}`).remove();
`'users'` надо убрать в опции конструктора

2021-03-30 11:12 UTC, awinogradov commented on packages/memory/src/lib/firebase.ts
> +const admin = require('firebase-admin');
А зачем через админа?

2021-03-30 11:12 UTC, awinogradov commented on packages/memory/src/lib/firebase.ts
> +    function spread(data:any): SaluteSession {
Но она же не any

2021-04-01 20:00 UTC, snyuryev commented on packages/memory/src/lib/firebase.ts
> +// eslint-disable-next-line no-unused-vars
done

2021-04-01 20:00 UTC, snyuryev commented on packages/memory/src/lib/firebase.ts
> + *
done

2021-04-01 20:00 UTC, snyuryev commented on packages/memory/src/lib/firebase.ts
> +const functions = require('firebase-functions');
done

2021-04-01 20:00 UTC, snyuryev commented on packages/memory/src/lib/firebase.ts
> +import {SaluteSessionStorage} from '@salutejs/memory';
done

2021-04-01 20:00 UTC, snyuryev commented on packages/memory/src/lib/firebase.ts
> +   * @param {id} id id.
done

2021-04-01 20:01 UTC, snyuryev commented on packages/memory/src/lib/firebase.ts
> +import {SaluteSessionStorage} from '@salutejs/memory';
done
позаимствовать интерфейс

2021-04-01 20:01 UTC, snyuryev commented on packages/memory/src/lib/firebase.ts
> +    return admin.database().ref(`users/${id}`).remove();
done
теперь есть ```path```

2021-04-01 20:04 UTC, snyuryev commented on packages/memory/src/lib/firebase.ts
> +const admin = require('firebase-admin');
так обычно и подключается
[пример](https://github.com/firebase/functions-samples/blob/854595932e2b0e2c7a9c1de16985f185cd2a9cac/lastmodified-tracking/functions/index.js#L19)

2021-04-03 11:39 UTC, awinogradov commented on packages/memory/package.json
> +    "firebase-admin": "^9.2.0",
Крыжечки надо убрать

2021-04-03 11:40 UTC, awinogradov commented on packages/memory/src/lib/firebase.ts
> +import functions = require('firebase-functions');
Почему импорт через require?

2021-04-03 11:40 UTC, awinogradov commented on packages/memory/src/lib/firebase.ts
> +import admin = require('firebase-admin');
Всё ещё не ясно почему через админа

2021-04-13 14:36 UTC, Turanchoks commented
@snyuryev Привет! Добьем PR?
– Давай перенесем в отдельный пакет (мы вынесем типы для стораджа в общий пакет types)
– Нужно поправить по комментариям импорты
– Кажется, не нужны cloud-functions, тут они подключены только чтобы вытащить в гугловой среде конфиг, но, кажется, это должно происходить на уровне приложения – наверное, конфигурацию стоит принимать стораджу при иницализации сверху, тогда уйдет зависимость от cloud functions в пакете.

Спасибо!

2021-04-13 15:37 UTC, snyuryev commented
@Turanchoks привет, с удовольствием)
- а как будет называться пакет?
- это про import вместо const? 
- да, перенесу

2021-04-19 07:35 UTC, Turanchoks commented
@snyuryev 
- а как будет называться пакет?
@salutejs/storage-firebase?
- Это про import вместо const?
import functions = require('firebase-functions');
- да, перенесу
🙏

2021-04-26 08:21 UTC, Turanchoks commented
@snyuryev пакет давай назовем `@salutejs/storage-adapter-firebase`, типы для SaluteSessionStorage перенесем в types на днях, зависимость можно будет убрать

2021-04-26 20:03 UTC, Turanchoks commented on packages/storage-adapter-firebase/src/lib/firebase.ts
> +    return (async () => {
зачем IIFE для await'а, если можно сделать resolve async'ом?

2021-04-26 20:05 UTC, Turanchoks commented on packages/storage-adapter-firebase/src/lib/firebase.ts
> +      .reduce((a, k) => ({ ...a, [k]: session[k] }), {});
Спредить в редьюсе не очень идея. Вообще тут session ведь всего на 4 поля, проще ручками скопировать, код будет понятнее и чище. И еще я не понял, а в каком случае в save передают session, у которого значения undefined?

2021-04-26 20:05 UTC, Turanchoks commented on packages/storage-adapter-firebase/src/lib/firebase.ts
> +    return this.db.ref(`${this.path}/${id}`).set(value);
this.db.ref(`${this.path}/${id}` – кажется, это можно вынести в хелпер

2021-04-30 10:03 UTC, awinogradov commented
Any progress here?

2021-05-02 15:53 UTC, snyuryev commented on packages/storage-adapter-firebase/src/lib/firebase.ts
> +  constructor(db: admin.database.Database, path: string = 'sessions') {
Прикидывать креденшелы не получится. Креденшелы используются для инициализации приложения firebase (где собраны все сервисы - БД, функции, сторадж...). Соответственно апп будет инициализрован раньше и повторно его не надо инициализовать (насколько я помню при повторной инициализации будет ошибка).

2021-05-04 12:20 UTC, Turanchoks commented on packages/storage-adapter-firebase/src/lib/firebase.ts
> +  constructor(db: admin.database.Database, path: string = 'sessions') {
Окей, а по остальным комментам посмотришь?

2021-05-05 15:12 UTC, snyuryev commented on packages/storage-adapter-firebase/src/lib/firebase.ts
> +  constructor(db: admin.database.Database, path: string = 'sessions') {
ок, посмотрю что пропустил.

2021-05-05 15:13 UTC, snyuryev commented on packages/storage-adapter-firebase/src/lib/firebase.ts
> +    return this.db.ref(`${this.path}/${id}`).set(value);
теперь это в getRef

2021-05-05 15:20 UTC, snyuryev commented on packages/storage-adapter-firebase/src/lib/firebase.ts
> +      .reduce((a, k) => ({ ...a, [k]: session[k] }), {});
Не уверен как сделать этот код более компактным. Как это упростить?
В save передаются session c undefined полями - это приведет к крашу в firebase. Поэтому такая фильтрация.

2021-05-05 15:20 UTC, snyuryev commented on packages/storage-adapter-firebase/README.md
> +> npm i -S @salutejs/memory
залил апдейт для ритме

2021-05-05 15:23 UTC, snyuryev commented on packages/storage-adapter-firebase/src/lib/firebase.ts
> +    return (async () => {
вроде бы не получается. получение данных в два этапа происходит:
асинхронно получаем snapshot  - **once()**
и далее получаем значение - **val()**

2021-05-18 11:22 UTC, sasha-tlt approved these changes

2021-05-18 13:04 UTC, Turanchoks approved these changes

2021-05-18 13:33 UTC, sasha-tlt commented
@awinogradov, аппрувни пр, пожалуйста, без тебя не получается смержить

2021-05-18 13:47 UTC, awinogradov approved these changes

2021-05-18 14:51 UTC, merged